# Generated by Django 5.1 on 2024-11-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_userscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certificates',
        ),
    ]
