# Generated by Django 5.1 on 2024-11-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_userprofile_achievements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='finishes',
            new_name='finishes_count',
        ),
    ]
