# Generated by Django 5.1 on 2024-11-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_finishes_userprofile_finishes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='finishes_count',
            new_name='finishes',
        ),
    ]
